### ISSUE TITLE
where is the plugin?

### ISSUE THREAD

**Issue by hidden-r4d** [GalaxzyDev/Deadcord-Client#1]
there's no releases section, and the repo doesn't have any *.js files. is there something im missing?

**Comment by GalaxzyDev** [comment]
We are still reworking the plugin, it is almost finished.

**Comment by hidden-r4d** [comment]
Got it, however i think there should be some mention of this somewhere to avoid confusion

**Comment by hidden-r4d** [comment]
plugin is now in the repo

**Comment by KeRimoYT** [comment]
> r

what is the name of plugin

**Comment by nerve-sys** [comment]
> what is the name of plugin

Deadcord.plugin.js
