### ISSUE TITLE
Deadcord.plugin.js: Could not be compiled

### ISSUE THREAD

**Issue by posercorpse** [GalaxzyDev/Deadcord-Client#2]
```
Deadcord.plugin.js: Could not be compiled. See console for details.
    at Object.loadAddon (<anonymous>:4:268126)
    at Object.loadAddon (<anonymous>:4:305956)
    at FSWatcher.<anonymous> (<anonymous>:4:266254)
```

Tested on:

Canary 116506 (5e71dd7)
BetterDiscord 1.5.2
Host 0.0.133 Linux 64-Bit (5.16.11-Arch1-1)

_and_

Stable 116506 (5e71dd7)
BetterDiscord 1.5.2
Host 0.0.17 Linux 64-Bit (5.16.11-Arch1-1)

**Comment by GalaxzyDev** [comment]
Thank you, I will take a look

**Comment by dox-net** [comment]
You may have downloaded the Plugin improperly, I had the same issue after I downloaded the Plugin with the "Save link as" option
Just copy+paste the code into a Js file, or clone the whole repo and use the Js file from there
